
# use this compose with existing traefik setup
# set traefik network name [TRAEFIK_NETWORK] in .env file

name: ${COMPOSE_NAME}

services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - packup-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  packup-app:
    image: ${APP_IMAGE}:${APP_IMAGE_TAG}
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=postgres-db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SSLMODE=${SSLMODE:-disable}
      - PORT=${PORT}
      - SESSION_SECURE=${SESSION_SECURE:-false}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_COMPOSE}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET_COMPOSE}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI_COMPOSE}
      - CHATBOT_ENABLED=${CHATBOT_ENABLED}
      - CHATBOT_API_URL=${CHATBOT_API_URL}
      - CHATBOT_API_TOKEN=${CHATBOT_API_TOKEN}
    depends_on:
      postgres-db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.packup-app.rule=Host(`${FULL_DOMAIN:-localhost}`)"
      - "traefik.http.routers.packup-app.entrypoints=websecure"
      - "traefik.http.routers.packup-app.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-myresolver}"
      - "traefik.http.services.packup-app.loadbalancer.server.port=${PORT}"

    networks:
      - default
      - traefik-proxy

networks:
  default:
    name: ${COMPOSE_NAME}
  traefik-proxy:
    name: ${TRAEFIK_NETWORK}
    external: true

volumes:
  packup-db-data:
