name: packup-dev-build

services:
  postgres:
    image: postgres:15
    container_name: packup-dev-db
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-packup}
    ports:
      - "5432:5432"
    networks:
      - packup-dev-build
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # container to help building node frontend
  node:
    image: node:24-alpine
    container_name: packup-node-dev
    working_dir: /app
    volumes:
      - ../frontend:/app
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - packup-dev-build

networks:
  packup-dev-build:
    name: packup-dev-build

volumes:
  pgdata:
